### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by lucaskapobassis** [cncjs/cncjs-pendant-tinyweb#16]
I haven't been able to connect to the tinyweb interface, with /pendant or /tinyweb
Here are two pictures that may help
![Capture](https://user-images.githubusercontent.com/46544342/58768214-e69e2780-85da-11e9-8277-33c4de451691.PNG)
![Capture1](https://user-images.githubusercontent.com/46544342/58768215-e69e2780-85da-11e9-8f05-ecb577365b94.PNG)

**Comment by adriantomic** [comment]
I'm having the same problem.

**Comment by MitchBradley** [comment]
The directory to use depends on how you loaded the tinyweb code into your host filesystem.  The actual code is in the src/ subdirectory, so if you cloned the whole tinyweb tree from git, you probably need to use

`  cncjs -m /pendant:/home/pi/tinyweb/src
`
There is no information in either of the above posts about the URL that was used to try and access the pendant code.

**Comment by lucaskapobassis** [comment]
Thanks Mitch, it now works!
